version: '3'

services:
  web:
    build: .
    expose:
      - 8000
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    depends_on:
      - db
    volumes:
      - static-volume:/app/staticfiles
  nginx:
    image: nginx:latest
    ports:
      - "8880:80"
      - "8443:443"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:Z
      - static-volume:/app/staticfiles
      - ./project_static:/app/project_static
    depends_on:
      - web
  db:
    image: postgres:13
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb

volumes:
  db-data:
  static-volume:
